### Check installation

The cluster is already preinstalled with OpenShift Serverless and OpenShift ServiceMesh operators (which is required for Serverless) and the Custom Resources are already created.

In this section, we will check the components of ServiceMesh and Serverless.

#### ServiceMesh

The control plane is installed automatically by Service Mesh operator in `knative-serving-ingress` namespace. 

Let's check the Control Plane custom resource.

[source,sh,role="copypaste"]
----
oc describe servicemeshcontrolplane -n knative-serving-ingress
----

Let's now check the deployed pods of the Control Plane:

[source,sh,role="copypaste"]
----
oc get pod -n knative-serving-ingress
----

----
NAME                                     READY   STATUS    RESTARTS   AGE
cluster-local-gateway-6647b96c4d-f6fcx   1/1     Running   1          23h
istio-citadel-79979464d-np24l            1/1     Running   1          23h
istio-galley-6bb46858c5-9kt4x            1/1     Running   1          23h
istio-ingressgateway-8465bbf788-qqpc8    1/1     Running   1          23h
istio-pilot-59fc69bd66-pdtpw             1/1     Running   1          23h
----

#### Serverless

As described in the intro section, the custom resource that Serverless Operator require in order to deploy its components for controlling the lifecycle of Serverless workloads is called KnativeServing.

Let's take a look at its definition

[source,sh,role="copypaste"]
----
oc get -o yaml knativeserving knative-serving -n knative-serving
----

And let's check its components

[source,sh,role="copypaste"]
----
oc get servicemonitor -n knative-serving
----

----
NAME         AGE
activator    23h
autoscaler   23h
controller   23h
----

As you can see, its components are: activator, autoscaler and controller


