id: "serverless-workshop"
name: "Deploying Serverless applications"

vars:
  KNATIVE_NS: test-knative
  OCP_DOMAIN: apps.pro1.mattiamascia.com

content:
  url: https://raw.githubusercontent.com/openlab-red/openshift-workshop/master

modules:
  activate:
  - serverless_intro
  - serverless_checks
  - serverless_first_app
  - serverless_revs_tags

